# Generated by Django 5.1.1 on 2024-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=25)),
                ('employment_type', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
